import "@/app/globals.css";
import Preloader from "./components/Preloader";
import CustomCursor from "./components/CustomCursor";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body id="top">
        <CustomCursor />
        <Preloader />
        {children}
      </body>
    </html>
  );
} 